if chain options are omitted write cert and chain to the file specifi…
oetiker/AcmeFetch pull request #18
Opened 2017-04-02 20:43 UTC by maettu

…ed in certOutput. E.g. for nginx

as discussed last week.

There is one point I am unsure how much checking there should be. Atm nonsensical combinations of chainOutput and chainFormat are possible; no enforcement of either both options present or absent.

2017-04-03 12:39 UTC, oetiker requested changes

2017-04-03 12:39 UTC, oetiker commented on bin/acmefetch
>              saveAway($cert->{keyOutput});
there is quite substantial code duplication ... how about just doing:

```perl
if ($cert->{chainOutput}){
￼   $fh->close();
   saveAway($cert->{chainOutput});
   $fh = IO::File->new( $cert->{chainOutput}, "w" )
￼                     || die "Write $cert->{chainOutput}: $!";
}
```
on line 330 of the original code and replace fh2 with fh

2017-04-03 19:41 UTC, maettu commented
updated

2017-04-04 16:26 UTC, oetiker requested changes

2017-04-04 16:26 UTC, oetiker commented on bin/acmefetch
>              my $chainData = convertCert($acme->chain(),'DER',$cert->{chainFormat});
there should be 

```perl
} else {
    $cert->{chainFormat} = $cert->{certFormat}
}
```

2017-04-04 16:27 UTC, oetiker commented on bin/acmefetch
>              my $chainData = convertCert($acme->chain(),'DER',$cert->{chainFormat});
oops that comment ended up one line to low

2017-04-06 07:50 UTC, merged

2017-04-06 07:50 UTC, oetiker commented
thanks